In [ ]:
import numpy as np

a=np.array(10)

print("Print A= ",a)

b=np.array([11,22,33])

print("Print B= ", b)

addition= np.add(a,b)

print("After Addition =", addition)

sub=np.subtract(b,a)

print("After Subtraction =",sub)

mul=np.multiply (a,b)

print("After Multiplcation =",mul)

div=np.divide (b,a)

print("After Division =",div)

div1=np.divide (b,11)

print("After Division =",div1)

Print A=  10
Print B=  [11 22 33]
After Addition = [21 32 43]
After Subtraction = [ 1 12 23]
After Multiplcation = [110 220 330]
After Division = [1.1 2.2 3.3]
After Division = [1. 2. 3.]


In [ ]:
a= np.array([0.16,3.33,1,133])

print(a)

rec=np.reciprocal(a) 
print(rec)

[  0.16   3.33   1.   133.  ]
[6.25      0.3003003 1.        0.0075188]


In [ ]:
a=np.array([9,27,81])

print(a)

pow=np.power(a,3)
print("after ^3 = ", pow)


b=np.array([1,2,1])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)

[ 9 27 81]
after ^3 =  [   729  19683 531441]
after b array elements as ^ =  [  9 729  81]


In [ ]:
a= np.array ([5,15,45])
b= np.array ([2,4,6])

print("A=", a)
print("B=", b)

mm=np.mod(a,b)

rm=np.remainder(a,b)

print("MOD=", mm)
print("REMAINDER=", rm)

A= [ 5 15 45]
B= [2 4 6]
MOD= [1 3 3]
REMAINDER= [1 3 3]


In [ ]:
a=np.array([-1.6j, 0.3j,10, 1+1j])
print(a)

print("real=",np.real(a))

print("imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))

[-0.-1.6j  0.+0.3j 10.+0.j   1.+1.j ]
real= [-0.  0. 10.  1.]
imaginary= [-1.6  0.3  0.   1. ]
Conjugate= [-0.+1.6j  0.-0.3j 10.-0.j   1.-1.j ]


In [ ]:
a=np.array ([12.0,4.6,111,0.56,20.25,52])

print(a)

print("after rounding up=", np.around(a))

print("after rounding up to 1st decimal value =", np.around(a,decimals=1))

[ 12.     4.6  111.     0.56  20.25  52.  ]
after rounding up= [ 12.   5. 111.   1.  20.  52.]
after rounding up to 1st decimal value = [ 12.    4.6 111.    0.6  20.2  52. ]


In [ ]:
a=np.array ([6.0,-5.3,100,-0.100,25.5,321])

print(a)

print('\n')

print(np.floor(a))

print(np.ceil(a))

[ 6.00e+00 -5.30e+00  1.00e+02 -1.00e-01  2.55e+01  3.21e+02]


[  6.  -6. 100.  -1.  25. 321.]
[  6.  -5. 100.  -0.  26. 321.]


In [ ]:
np= np.array([1, 2, 3])
print(np)

[1 2 3]


In [ ]:
import numpy as npp
a = npp.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [ ]:
ab=np.empty(2)
print(ab)

[0. 0.]


In [ ]:
a=np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [ ]:
a=np.arange(3,9,2)
print(a)

[3 5 7]


In [ ]:
y = np.ones(2, dtype=int)
print(y)
y

[1 1]


array([1, 1])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)


a=np.delete(a, 2)
print(a)

[1 2 3 4 5 6 7 8]
[1 2 4 5 6 7 8]


In [ ]:
a = np.array([21, 42, 49, 1, 85, 67, 7, 81])
print(a)


a=np.sort(a)
print(a)

[21 42 49  1 85 67  7 81]
[ 1  7 21 42 49 67 81 85]


In [ ]:

arr = np.array([[2, 4, 6], [1, 2, 4]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)

[[2 4 6]
 [1 2 4]]
dimensions =  2


In [ ]:
arr = np.array([[[2, 4, 5], [1, 2, 3]], [[10, 20, 30], [21, 42, 84]]])
a=arr.ndim
b=arr.size
print(arr) 
print("dimensions = ", a)
print("size = ", b)

[[[ 2  4  5]
  [ 1  2  3]]

 [[10 20 30]
  [21 42 84]]]
dimensions =  3
size =  12


In [ ]:
a = np.array(50)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print("dimension= ", a.ndim)
print(b)
print("dimension= ", b.ndim)
print(c)
print("dimension= ", c.ndim)
print(d)
print("dimension= ", d.ndim)

50
dimension=  0
[1 2 3 4 5]
dimension=  1
[[1 2 3]
 [4 5 6]]
dimension=  2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension=  3


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


In [ ]:
a = np.arange(5)
print(a)

b = a.reshape(1,5)
print(b)

[0 1 2 3 4]
[[0 1 2 3 4]]


**NumpyArraySearch**



In [ ]:
import numpy as np

arr = np.array([10,11,12,4,5,12])

x = np.where(arr == 2)

print(x) 

(array([], dtype=int64),)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

In [ ]:
import numpy as np

arr = np.array([10, 12, 23, 34, 45, 56, 67, 78])

x = np.where(arr%2 == 1)

print(x) 

(array([2, 4, 6]),)


In [ ]:
import numpy as np

arr = np.array([6, 7, 18, 19])

x = np.searchsorted(arr,11)

print(x) 

2


In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9, side='right')

print(x) 

4


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.searchsorted(arr, [1, 3, 4])

print(x) 

[0 2 3]


**ArraySlicing**


In [ ]:
import numpy as np

arr = np.array([11, 21 ,32, 45,63,24,38])

print(arr[1:5]) 

[21 32 45 63]


In [ ]:
import numpy as np

arr = np.array([11, 21 ,32, 45,63,24,38])

print(arr[4:]) 

[63 24 38]


In [ ]:
import numpy as np

arr = np.array([11, 21 ,32, 45,63,24,38])

print(arr[:4]) 

[11 21 32 45]


In [ ]:
import numpy as np

arr = np.array([11, 21 ,32, 45,63,24,38])

print(arr[-3:-2])

[63]


In [ ]:
import numpy as np

arr = np.array([11, 21 ,32, 45,63,24,38])

print(arr[1:2:3]) 

[21]


In [ ]:
import numpy as np

arr = np.array([11, 21 ,32, 45,63,24,38])

print(arr[::1]) 

[11 21 32 45 63 24 38]


In [ ]:
import numpy as np

arr = np.array([[11, 21 ,32,26], [45,63,24,38]])

print(arr[1, 1:2]) 

[63]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])

print(arr[2,0:2]) 

[11 12]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[22,33,44,55,66]])

print(arr[0:3, 2])

[ 3  8 44]


In [ ]:
import numpy as np

arr = np.array([[11, 21 ,32,26], [45,63,24,38]])

print(arr[0:2, 1:4]) 

[[21 32 26]
 [63 24 38]]


**ArraySplit**


In [ ]:
import numpy as np

arr = np.array([11,13,15,17,19])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([11, 13]), array([15, 17]), array([19])]


In [ ]:
import numpy as np

arr = np.array([11,13,15,17,19])

newarr = np.array_split(arr, 2)

print(newarr[0])
print(newarr[1])
 

[11 13 15]
[17 19]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2]) 



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]
 [11 12]]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)
print("\n")
print(newarr[0])
print(newarr[1])




[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])

print(newarr[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


**numpy concat, stack**

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30])

arr2 = np.array([40, 50, 60])

arr = np.concatenate((arr1, arr2))

print(arr) 

[10 20 30 40 50 60]


In [ ]:
import numpy as np

arr1 = np.array([[1, 3], [5, 7]])

print("arr1=", arr1) 

arr2 = np.array([[5, 6], [7, 8]])

print("arr2=", arr2) 

print("after concatenation =")

arr = np.concatenate((arr1, arr2), axis=1)

print(arr) 

arr1= [[1 3]
 [5 7]]
arr2= [[5 6]
 [7 8]]
after concatenation =
[[1 3 5 6]
 [5 7 7 8]]


In [ ]:
import numpy as np

arr1 = np.array([1, 3, 5])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 3 5 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([1, 3, 5])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 3 5]
 [4 5 6]]


In [ ]:
a = np.array([1,3,5])

b = np.array([4,5,6])

print("hstack =", np.hstack((a,b)))

print("vstack =", np.vstack((a,b)))

a = np.array([[1],[3],[5]])

b = np.array([[4],[5],[6]])

print("hstack =", np.hstack((a,b)))

print("vstack =", np.vstack((a,b)))


hstack = [1 3 5 4 5 6]
vstack = [[1 3 5]
 [4 5 6]]
hstack = [[1 4]
 [3 5]
 [5 6]]
vstack = [[1]
 [3]
 [5]
 [4]
 [5]
 [6]]


In [ ]:
a = np.array([[1,2,3],[10,20,30],[110,220,330],[1100,2200,3300]])

b = np.array([[7,8,9],[77,88,99],[700,800,900],[7770,8880,9990]])

print("\nhstack =\n", np.hstack((a,b)))

print("\nvstack =\n", np.vstack((a,b)))

arr = np.concatenate((a, b), axis=0)
print("\n concatenate at axis 0=\n",arr)

arr1 = np.concatenate((a, b), axis=1)
print("\n concatenate at axis 1=\n",arr1)


hstack =
 [[   1    2    3    7    8    9]
 [  10   20   30   77   88   99]
 [ 110  220  330  700  800  900]
 [1100 2200 3300 7770 8880 9990]]

vstack =
 [[   1    2    3]
 [  10   20   30]
 [ 110  220  330]
 [1100 2200 3300]
 [   7    8    9]
 [  77   88   99]
 [ 700  800  900]
 [7770 8880 9990]]

 concatenate at axis 0=
 [[   1    2    3]
 [  10   20   30]
 [ 110  220  330]
 [1100 2200 3300]
 [   7    8    9]
 [  77   88   99]
 [ 700  800  900]
 [7770 8880 9990]]

 concatenate at axis 1=
 [[   1    2    3    7    8    9]
 [  10   20   30   77   88   99]
 [ 110  220  330  700  800  900]
 [1100 2200 3300 7770 8880 9990]]


In [ ]:
a= np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[7,8,9]])
print(c)

[[7 8 9]]


In [ ]:
np.append(a,c, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
a = np.array([2,4,6])
b = np.array([1,3])
np.concatenate((a,b))

array([2, 4, 6, 1, 3])

In [ ]:
np.r_[a,b]

array([2, 4, 6, 1, 3])

In [ ]:
a = np.array([1,3,5])
b = np.array([2,4,6])
np.stack([a,b]).reshape(-1)

array([1, 3, 5, 2, 4, 6])

In [ ]:
a = np.array([1, 2,3])
b = np.array([5, 6,7])
np.stack([a,b])

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a = np.array([[1,2,3],[10,20,30],[110,220,330],[1100,2200,3300]])

b = np.array([[7,8,9],[77,88,99],[700,800,900],[7770,8880,9990]])

print("\nhstack =\n", np.hstack((a,b)))
print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[   1    2    3    7    8    9]
 [  10   20   30   77   88   99]
 [ 110  220  330  700  800  900]
 [1100 2200 3300 7770 8880 9990]]

vstack =
 [[   1    2    3]
 [  10   20   30]
 [ 110  220  330]
 [1100 2200 3300]
 [   7    8    9]
 [  77   88   99]
 [ 700  800  900]
 [7770 8880 9990]]


In [ ]:
a = np.array([[1],[3],[5]])

b = np.array([[7],[9],[11]])

print("\nhstack =\n", np.hstack((a,b)))
print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[ 1  7]
 [ 3  9]
 [ 5 11]]

vstack =
 [[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [ ]:
a = np.array([[1,2],[3,4]])

b = np.array([[5,6],[7,8]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[1 2 5 6]
 [3 4 7 8]]

======next print======

vstack =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np
a = np.array([[1, 3], [5, 7]])
b = np.array([[5, 7]])
np.concatenate((a, b), axis=0)

array([[1, 3],
       [5, 7],
       [5, 7]])

In [ ]:
np.vstack((a,b))

array([[1, 3],
       [5, 7],
       [5, 7]])

In [ ]:
np.concatenate((a, b), axis=1)

ValueError: ignored

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 3, 5],
       [5, 7, 7]])

In [ ]:
import numpy as np
a = np.array([[1, 3], [5, 7]])
b = np.array([5, 7])
bb= np.array([[5, 7],[9,11]])
cc=b.T

print("vstack=",np.vstack((a,cc)))

print("hstack=",np.hstack((a,bb)))

vstack= [[1 3]
 [5 7]
 [5 7]]
hstack= [[ 1  3  5  7]
 [ 5  7  9 11]]


In [ ]:
a = np.array((1,2,3))
b = np.array((7,8,9))
print(a)
print(b)

print("vstack\n")
print(np.vstack((a,b)))
print("concatenate\n")
print(np.concatenate([a.reshape(1,3),b.reshape(1,3)]))
print("stack\n")
print(np.stack((a,b),axis=1))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 1))
print("stack\n")
print(np.stack((a,b),axis=0))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 0))

[1 2 3]
[7 8 9]
vstack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]
stack

[[1 7]
 [2 8]
 [3 9]]
concatenate

[[1 2 3 7 8 9]]
stack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]
